package com.ylf.netty.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scratch.proto

public final class MyDataInfo {
  private MyDataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MyData.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.MyData.Type type = 1;</code>
     */
    MyData.Type getType();

    /**
     * <code>.Nums num = 2;</code>
     */
    boolean hasNum();
    /**
     * <code>.Nums num = 2;</code>
     */
    Nums getNum();
    /**
     * <code>.Nums num = 2;</code>
     */
    NumsOrBuilder getNumOrBuilder();

    /**
     * <code>.Res res = 3;</code>
     */
    boolean hasRes();
    /**
     * <code>.Res res = 3;</code>
     */
    Res getRes();
    /**
     * <code>.Res res = 3;</code>
     */
    ResOrBuilder getResOrBuilder();

    public MyData.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code MyData}
   */
  public  static final class MyData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyData)
      MyDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyData.newBuilder() to construct.
    private MyData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyData() {
      type_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              Nums.Builder subBuilder = null;
              if (dataCase_ == 2) {
                subBuilder = ((Nums) data_).toBuilder();
              }
              data_ =
                  input.readMessage(Nums.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Nums) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 2;
              break;
            }
            case 26: {
              Res.Builder subBuilder = null;
              if (dataCase_ == 3) {
                subBuilder = ((Res) data_).toBuilder();
              }
              data_ =
                  input.readMessage(Res.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Res) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_MyData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_MyData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyData.class, Builder.class);
    }

    /**
     * Protobuf enum {@code MyData.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *proto3要求枚举类型编号从0开始
       * </pre>
       *
       * <code>Num = 0;</code>
       */
      Num(0),
      /**
       * <code>Res = 1;</code>
       */
      Res(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *proto3要求枚举类型编号从0开始
       * </pre>
       *
       * <code>Num = 0;</code>
       */
      public static final int Num_VALUE = 0;
      /**
       * <code>Res = 1;</code>
       */
      public static final int Res_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return Num;
          case 1: return Res;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MyData.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MyData.Type)
    }

    private int dataCase_ = 0;
    private Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite {
      NUM(2),
      RES(3),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 2: return NUM;
          case 3: return RES;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.MyData.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MyData.Type type = 1;</code>
     */
    public Type getType() {
      @SuppressWarnings("deprecation")
      Type result = Type.valueOf(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }

    public static final int NUM_FIELD_NUMBER = 2;
    /**
     * <code>.Nums num = 2;</code>
     */
    public boolean hasNum() {
      return dataCase_ == 2;
    }
    /**
     * <code>.Nums num = 2;</code>
     */
    public Nums getNum() {
      if (dataCase_ == 2) {
         return (Nums) data_;
      }
      return Nums.getDefaultInstance();
    }
    /**
     * <code>.Nums num = 2;</code>
     */
    public NumsOrBuilder getNumOrBuilder() {
      if (dataCase_ == 2) {
         return (Nums) data_;
      }
      return Nums.getDefaultInstance();
    }

    public static final int RES_FIELD_NUMBER = 3;
    /**
     * <code>.Res res = 3;</code>
     */
    public boolean hasRes() {
      return dataCase_ == 3;
    }
    /**
     * <code>.Res res = 3;</code>
     */
    public Res getRes() {
      if (dataCase_ == 3) {
         return (Res) data_;
      }
      return Res.getDefaultInstance();
    }
    /**
     * <code>.Res res = 3;</code>
     */
    public ResOrBuilder getResOrBuilder() {
      if (dataCase_ == 3) {
         return (Res) data_;
      }
      return Res.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Type.Num.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (dataCase_ == 2) {
        output.writeMessage(2, (Nums) data_);
      }
      if (dataCase_ == 3) {
        output.writeMessage(3, (Res) data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Type.Num.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Nums) data_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Res) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyData)) {
        return super.equals(obj);
      }
      MyData other = (MyData) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getDataCase().equals(
          other.getDataCase());
      if (!result) return false;
      switch (dataCase_) {
        case 2:
          result = result && getNum()
              .equals(other.getNum());
          break;
        case 3:
          result = result && getRes()
              .equals(other.getRes());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (dataCase_) {
        case 2:
          hash = (37 * hash) + NUM_FIELD_NUMBER;
          hash = (53 * hash) + getNum().hashCode();
          break;
        case 3:
          hash = (37 * hash) + RES_FIELD_NUMBER;
          hash = (53 * hash) + getRes().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyData)
        MyDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_MyData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_MyData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyData.class, Builder.class);
      }

      // Construct using MyDataInfo.MyData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_MyData_descriptor;
      }

      @Override
      public MyData getDefaultInstanceForType() {
        return MyData.getDefaultInstance();
      }

      @Override
      public MyData build() {
        MyData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MyData buildPartial() {
        MyData result = new MyData(this);
        result.type_ = type_;
        if (dataCase_ == 2) {
          if (numBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = numBuilder_.build();
          }
        }
        if (dataCase_ == 3) {
          if (resBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = resBuilder_.build();
          }
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyData) {
          return mergeFrom((MyData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyData other) {
        if (other == MyData.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getDataCase()) {
          case NUM: {
            mergeNum(other.getNum());
            break;
          }
          case RES: {
            mergeRes(other.getRes());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MyData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MyData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.MyData.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MyData.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MyData.Type type = 1;</code>
       */
      public Type getType() {
        @SuppressWarnings("deprecation")
        Type result = Type.valueOf(type_);
        return result == null ? Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.MyData.Type type = 1;</code>
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MyData.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Nums, Nums.Builder, NumsOrBuilder> numBuilder_;
      /**
       * <code>.Nums num = 2;</code>
       */
      public boolean hasNum() {
        return dataCase_ == 2;
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      public Nums getNum() {
        if (numBuilder_ == null) {
          if (dataCase_ == 2) {
            return (Nums) data_;
          }
          return Nums.getDefaultInstance();
        } else {
          if (dataCase_ == 2) {
            return numBuilder_.getMessage();
          }
          return Nums.getDefaultInstance();
        }
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      public Builder setNum(Nums value) {
        if (numBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          numBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      public Builder setNum(
          Nums.Builder builderForValue) {
        if (numBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          numBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      public Builder mergeNum(Nums value) {
        if (numBuilder_ == null) {
          if (dataCase_ == 2 &&
              data_ != Nums.getDefaultInstance()) {
            data_ = Nums.newBuilder((Nums) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 2) {
            numBuilder_.mergeFrom(value);
          }
          numBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      public Builder clearNum() {
        if (numBuilder_ == null) {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
          }
          numBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      public Nums.Builder getNumBuilder() {
        return getNumFieldBuilder().getBuilder();
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      public NumsOrBuilder getNumOrBuilder() {
        if ((dataCase_ == 2) && (numBuilder_ != null)) {
          return numBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 2) {
            return (Nums) data_;
          }
          return Nums.getDefaultInstance();
        }
      }
      /**
       * <code>.Nums num = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Nums, Nums.Builder, NumsOrBuilder>
          getNumFieldBuilder() {
        if (numBuilder_ == null) {
          if (!(dataCase_ == 2)) {
            data_ = Nums.getDefaultInstance();
          }
          numBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Nums, Nums.Builder, NumsOrBuilder>(
                  (Nums) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 2;
        onChanged();;
        return numBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Res, Res.Builder, ResOrBuilder> resBuilder_;
      /**
       * <code>.Res res = 3;</code>
       */
      public boolean hasRes() {
        return dataCase_ == 3;
      }
      /**
       * <code>.Res res = 3;</code>
       */
      public Res getRes() {
        if (resBuilder_ == null) {
          if (dataCase_ == 3) {
            return (Res) data_;
          }
          return Res.getDefaultInstance();
        } else {
          if (dataCase_ == 3) {
            return resBuilder_.getMessage();
          }
          return Res.getDefaultInstance();
        }
      }
      /**
       * <code>.Res res = 3;</code>
       */
      public Builder setRes(Res value) {
        if (resBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          resBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.Res res = 3;</code>
       */
      public Builder setRes(
          Res.Builder builderForValue) {
        if (resBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          resBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.Res res = 3;</code>
       */
      public Builder mergeRes(Res value) {
        if (resBuilder_ == null) {
          if (dataCase_ == 3 &&
              data_ != Res.getDefaultInstance()) {
            data_ = Res.newBuilder((Res) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 3) {
            resBuilder_.mergeFrom(value);
          }
          resBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.Res res = 3;</code>
       */
      public Builder clearRes() {
        if (resBuilder_ == null) {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
          }
          resBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Res res = 3;</code>
       */
      public Res.Builder getResBuilder() {
        return getResFieldBuilder().getBuilder();
      }
      /**
       * <code>.Res res = 3;</code>
       */
      public ResOrBuilder getResOrBuilder() {
        if ((dataCase_ == 3) && (resBuilder_ != null)) {
          return resBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 3) {
            return (Res) data_;
          }
          return Res.getDefaultInstance();
        }
      }
      /**
       * <code>.Res res = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Res, Res.Builder, ResOrBuilder>
          getResFieldBuilder() {
        if (resBuilder_ == null) {
          if (!(dataCase_ == 3)) {
            data_ = Res.getDefaultInstance();
          }
          resBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Res, Res.Builder, ResOrBuilder>(
                  (Res) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 3;
        onChanged();;
        return resBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyData)
    }

    // @@protoc_insertion_point(class_scope:MyData)
    private static final MyData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyData();
    }

    public static MyData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyData>
        PARSER = new com.google.protobuf.AbstractParser<MyData>() {
      @Override
      public MyData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MyData> getParserForType() {
      return PARSER;
    }

    @Override
    public MyData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NumsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Nums)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 n1 = 1;</code>
     */
    int getN1();

    /**
     * <code>int32 n2 = 2;</code>
     */
    int getN2();
  }
  /**
   * Protobuf type {@code Nums}
   */
  public  static final class Nums extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Nums)
      NumsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Nums.newBuilder() to construct.
    private Nums(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Nums() {
      n1_ = 0;
      n2_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Nums(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              n1_ = input.readInt32();
              break;
            }
            case 16: {

              n2_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_Nums_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_Nums_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Nums.class, Builder.class);
    }

    public static final int N1_FIELD_NUMBER = 1;
    private int n1_;
    /**
     * <code>int32 n1 = 1;</code>
     */
    public int getN1() {
      return n1_;
    }

    public static final int N2_FIELD_NUMBER = 2;
    private int n2_;
    /**
     * <code>int32 n2 = 2;</code>
     */
    public int getN2() {
      return n2_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (n1_ != 0) {
        output.writeInt32(1, n1_);
      }
      if (n2_ != 0) {
        output.writeInt32(2, n2_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (n1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, n1_);
      }
      if (n2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, n2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Nums)) {
        return super.equals(obj);
      }
      Nums other = (Nums) obj;

      boolean result = true;
      result = result && (getN1()
          == other.getN1());
      result = result && (getN2()
          == other.getN2());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + N1_FIELD_NUMBER;
      hash = (53 * hash) + getN1();
      hash = (37 * hash) + N2_FIELD_NUMBER;
      hash = (53 * hash) + getN2();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Nums parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nums parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nums parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nums parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nums parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nums parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nums parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Nums parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Nums parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Nums parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Nums parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Nums parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Nums prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Nums}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Nums)
        NumsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_Nums_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_Nums_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Nums.class, Builder.class);
      }

      // Construct using MyDataInfo.Nums.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        n1_ = 0;

        n2_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_Nums_descriptor;
      }

      @Override
      public Nums getDefaultInstanceForType() {
        return Nums.getDefaultInstance();
      }

      @Override
      public Nums build() {
        Nums result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Nums buildPartial() {
        Nums result = new Nums(this);
        result.n1_ = n1_;
        result.n2_ = n2_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Nums) {
          return mergeFrom((Nums)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Nums other) {
        if (other == Nums.getDefaultInstance()) return this;
        if (other.getN1() != 0) {
          setN1(other.getN1());
        }
        if (other.getN2() != 0) {
          setN2(other.getN2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Nums parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Nums) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int n1_ ;
      /**
       * <code>int32 n1 = 1;</code>
       */
      public int getN1() {
        return n1_;
      }
      /**
       * <code>int32 n1 = 1;</code>
       */
      public Builder setN1(int value) {
        
        n1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 n1 = 1;</code>
       */
      public Builder clearN1() {
        
        n1_ = 0;
        onChanged();
        return this;
      }

      private int n2_ ;
      /**
       * <code>int32 n2 = 2;</code>
       */
      public int getN2() {
        return n2_;
      }
      /**
       * <code>int32 n2 = 2;</code>
       */
      public Builder setN2(int value) {
        
        n2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 n2 = 2;</code>
       */
      public Builder clearN2() {
        
        n2_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Nums)
    }

    // @@protoc_insertion_point(class_scope:Nums)
    private static final Nums DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Nums();
    }

    public static Nums getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Nums>
        PARSER = new com.google.protobuf.AbstractParser<Nums>() {
      @Override
      public Nums parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Nums(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Nums> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Nums> getParserForType() {
      return PARSER;
    }

    @Override
    public Nums getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Res)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 res = 1;</code>
     */
    int getRes();
  }
  /**
   * Protobuf type {@code Res}
   */
  public  static final class Res extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Res)
      ResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Res.newBuilder() to construct.
    private Res(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Res() {
      res_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Res(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              res_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_Res_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_Res_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Res.class, Builder.class);
    }

    public static final int RES_FIELD_NUMBER = 1;
    private int res_;
    /**
     * <code>int32 res = 1;</code>
     */
    public int getRes() {
      return res_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (res_ != 0) {
        output.writeInt32(1, res_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (res_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, res_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Res)) {
        return super.equals(obj);
      }
      Res other = (Res) obj;

      boolean result = true;
      result = result && (getRes()
          == other.getRes());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RES_FIELD_NUMBER;
      hash = (53 * hash) + getRes();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Res parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Res parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Res parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Res parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Res parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Res parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Res parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Res parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Res parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Res parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Res parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Res parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Res prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Res}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Res)
        ResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_Res_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_Res_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Res.class, Builder.class);
      }

      // Construct using MyDataInfo.Res.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        res_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_Res_descriptor;
      }

      @Override
      public Res getDefaultInstanceForType() {
        return Res.getDefaultInstance();
      }

      @Override
      public Res build() {
        Res result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Res buildPartial() {
        Res result = new Res(this);
        result.res_ = res_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Res) {
          return mergeFrom((Res)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Res other) {
        if (other == Res.getDefaultInstance()) return this;
        if (other.getRes() != 0) {
          setRes(other.getRes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Res parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Res) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int res_ ;
      /**
       * <code>int32 res = 1;</code>
       */
      public int getRes() {
        return res_;
      }
      /**
       * <code>int32 res = 1;</code>
       */
      public Builder setRes(int value) {
        
        res_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 res = 1;</code>
       */
      public Builder clearRes() {
        
        res_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Res)
    }

    // @@protoc_insertion_point(class_scope:Res)
    private static final Res DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Res();
    }

    public static Res getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Res>
        PARSER = new com.google.protobuf.AbstractParser<Res>() {
      @Override
      public Res parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Res(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Res> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Res> getParserForType() {
      return PARSER;
    }

    @Override
    public Res getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Nums_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Nums_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Res_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Res_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rscratch.proto\"q\n\006MyData\022\032\n\004type\030\001 \001(\0162" +
      "\014.MyData.Type\022\024\n\003num\030\002 \001(\0132\005.NumsH\000\022\023\n\003r" +
      "es\030\003 \001(\0132\004.ResH\000\"\030\n\004Type\022\007\n\003Num\020\000\022\007\n\003Res" +
      "\020\001B\006\n\004data\"\036\n\004Nums\022\n\n\002n1\030\001 \001(\005\022\n\n\002n2\030\002 \001" +
      "(\005\"\022\n\003Res\022\013\n\003res\030\001 \001(\005B\016B\nMyDataInfoH\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MyData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyData_descriptor,
        new String[] { "Type", "Num", "Res", "Data", });
    internal_static_Nums_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Nums_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Nums_descriptor,
        new String[] { "N1", "N2", });
    internal_static_Res_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Res_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Res_descriptor,
        new String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
